services:
  - type: web
    name: django-files-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # User will paste their Neon PostgreSQL connection string here
